<a href="https://colab.research.google.com/github/bigirimanainnocent12/R-seaux-de-neurones/blob/main/Reseaux_de_neurones.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Création des tenseurs**

In [1]:
import torch

# **Tenseur en PyTorch **

# **un scalaire**

In [9]:
tenseur=torch.tensor(1.0)
tenseur.item()

1.0

# **Vecteur**

In [8]:
vec=torch.tensor([1,5,2,3,65,4,7])
vec[0:3]

tensor([1, 5, 2])

# **Matrice **

In [21]:
mat=torch.tensor([[14,5,3,6,5],[54,2,58,69,785],[14,58,65,65,65]])
mat[:][0]

tensor([14,  5,  3,  6,  5])

In [26]:
mat[:2,:2]

tensor([[14,  5],
        [54,  2]])

In [27]:
mat

tensor([[ 14,   5,   3,   6,   5],
        [ 54,   2,  58,  69, 785],
        [ 14,  58,  65,  65,  65]])